#!/bin/sh
# https://github.com/muennich/dotfiles/blob/master/.cmus/cover-viewer

for file in "$@"; do
	for cover in "${file%/*}"/cover.*; do
		if [ -f "$cover" ]; then
			echo "$cover"
		fi
	done
done \
  | sort | uniq | sxiv -ibqsd -g 400x400 &
